### PR TITLE
Changed from global to local variable assignments

### PR DESCRIPTION
**Pull request by britzl**
Don't pollute the global scope!

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Hi @britzl,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by mattwynne** [comment]
@britzl thanks for your contribution, I'm sorry it took us so long to merge it in - we don't have anyone maintaining this library anymore.

Would you be interested in helping us with that?

**Comment by britzl** [comment]
@mattwynne not a problem!

I was using Cucumber a lot while working at King. Nowadays I work full-time on the Defold game engine so I'm still very much invested in the Lua language. I have limited time, but it can definitely help out. What do you need help with? Go through open issues and pull requests?

**Comment by mattwynne** [comment]
Fabulous! 🎉

Yes, essentially it would be:

1) working with any open pull requests to get them merged in a satisfactory state
2) keeping the test infrastructure up to date (I see we're using Travis on this project, but we've generally moved everything to GitHub Actions now)
3) triaging issues and, where possible, coaching others to submit PRs to solve them, or creating your own
4) making releases whenever there's something useful ready to ship

If you want to chat 🍵  about this, you're welcome to join us in our [community Slack](https://cucumber.io/community#slack) in the [#committers](https://cucumberbdd.slack.com/archives/C62D0FK0E) channel 😄 

If you'd prefer a call, you can book a slot with me [here](https://calendly.com/mattwynne).

**Comment by britzl** [comment]
@mattwynne I'll get in touch after Christmas!

**Pull request merged**
