### PR TITLE
Feature/end scenario hook

### PR DESCRIPTION
**Pull request by britzl**
I think cucumber-lua could benefit from an After-hooks that can be called after each scenario (in end_scenario). Implemented using the same principle as the already existing begin_scenario and Before-hook

### CODE REVIEW

**Comment by britzl** [comment]
@joshski What's your thought on this? I think it makes sense to provide an After hook to match the Before hook. I've seen it implemented in cucumber-js for instance.

**Comment by joshski** [comment]
Hi @britzl,

Looks like a good idea. Any chance you could rebase this against master and write a spec for it?

**Comment by britzl** [comment]
I'm not sure what kind of specification you're looking for, but I went ahead and added some information about the Before, After, BeforeStep and AfterStep hooks to the readme file. Was that what you had in mind?

**Comment by mondwan** [comment]
Hello, what is the status for this pull request? Actually, I really need this `after hook` implementation. Why this is still pending?

**Comment by mattwynne** [comment]
Because you haven’t implemented it yet :)

**Comment by xtrasimplicity** [comment]
@britzl, I think he's referring to a cucumber feature, or some other form of test case. Assuming this was rebased onto master and the specs were present, I think we could look at merging this. :)

**Comment by britzl** [comment]
Done! (better late than never I guess)

**Pull request merged**
