### PR TITLE
Support for lua 5.3

### PR DESCRIPTION
**Pull request by admo**

### CODE REVIEW

**Review by dskripin — APPROVED** [review]
Verified locally

**Comment by joshski** [comment]
Thanks @admo this is great.

I installed everything locally and ran the tests under Lua 5.3 and it worked for me.

I must admit I'm a bit out of the loop having not used Lua much in a few years. Are these changes backwards-compatible with Lua 5.2?

**Comment by admo** [comment]
Hi @joshski. I've checked that these changes are compatible wit Lua 5.1. According to the changelog of the Lua, I assume that they are also compatible with lua 5.2.

However, I can also check with lua 5.2.

**Comment by admo** [comment]
@joshski 
I've checked with Lua 5.2. I can confirm that my test suite also works with Lua 5.2 and with changed cucumber-lua.

**Comment by admo** [comment]
Hi @joshski!
Are you going to merge my change? :)

**Comment by xtrasimplicity** [comment]
@admo, Could you please rebase your changes onto the latest master? Assuming the CI tests pass, we should be able to merge this. :)

**Comment by admo** [comment]
@xtrasimplicity I've cleaned my branch and rebased to upstream master.

**Comment by xtrasimplicity** [comment]
Thanks @admo. I'll merge this now. :)

**Comment by aslakhellesoy** [comment]
Hi @admo,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Pull request merged**
