### PR TITLE
source_hotfix: fixes issue with lua-cucumber not working with current…

### PR DESCRIPTION
**Pull request by Bigfootmech**
… ruby & cucumber versions

https://github.com/cucumber/cucumber-lua/issues/7

### CODE REVIEW

**Review by admo — APPROVED** [review]
Verified locally.

**Comment by xtrasimplicity** [comment]
@Bigfootmech, could you please rebase your changes onto master, so that the CI test suite will run through it? If it's all good, we can probably merge this.

**Comment by litespring** [comment]
@admo  I was  wondering if this change can be merged  ?.

**Comment by admo** [comment]
@litespring I'm not sure if I'm the right person to decide.

**Comment by mpkorstanje** [comment]
This repository hasn't had an active maintainer for a while.

If someone can re=submit a PR to trigger the CI, then I can merge it.

**Pull request closed without merging**
