### PR TITLE
Adding Travis CI

### PR DESCRIPTION
**Pull request by xtrasimplicity**
As per https://github.com/cucumber/cucumber-lua/issues/11, it would be great to have a continuous integration setup to ensure tests are run on merge. :)

---
This change is [Reviewable](https://reviewable.io/reviews/cucumber/cucumber-lua/12)

### CODE REVIEW

**Comment by olleolleolle** [comment]
This is cool work.

`lua: spec/runner.lua:1: module 'lfs' not found:`

**Comment by xtrasimplicity** [comment]
Yep, it turns out there's a few dependencies we need. I'm not too familiar with Lua, so someone else may be able to tidy up a little, but installing `busted` installs all of the dependencies we need. :)

**Comment by xtrasimplicity** [comment]
All done! :) @olleolleolle, Are you happy for me to squash and merge this?

**Review by olleolleolle — APPROVED** [review]
This CI hook helps development a lot!

**Pull request merged**
